name: demo
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened,edited,closed,synchronize]
    branches: main
env:
  MONGODB_DB_NAME: TEST
jobs:
  test:
    runs-on: ubuntu-22.04
   # environment: testing
    defaults:
      run:
        shell: bash
    env:
      MONGODB_CLUSTER_ADDRESS: ${{vars.MONGODB_CLUSTER_ADDRESS}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      PORT: ${{vars.PORT}}
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v7
        with:
           node-version: '20'
           cache: 'npm'
      - name: cacheing
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: xx-${{hashFiles('**/package-lock.json')}}
      - name: dep
        run: npm install
      
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: test
        run: npm test
      - name:
        run: |
          echo $MONGODB_CLUSTER_ADDRESS
          echo ${{vars.MONGODB_CLUSTER_ADDRESS}}
          
        













      
